# Site Settings
baseurl: ""
url : "https://zeningzheng.github.io"

# Blog Settings
theme_settings :
  title : Zening Zheng
  favicon : assets/favicon.ico

  # Profile Settings
  profile :
    image : assets/img/zena.jpg
    username : Zening (Zena) Zheng
    description : Master of Psychology in Behavioral Data Science, UvA<br>Seeking for 2022 Intern
    education :
      - start : 2015-09
        end : 2019-06
        experience : Bachelor in Quantitative Psychology, Jiangxi Normal University, Honours Degree

      - start : 2021-09
        end : Precent
        experience : Master of Psychology in Behavioral Data Science, Universirty of Amsterdam
        anticipated course : Behavioral Data Science Toolbox (Data Visualization/SQL/Consultancy), Big Data Analytics, Deep Learning in Python, Internship Data-Driven Consultancy, Psychometrics
    skills : 
      - skill : Python, R, SPSS, Mplus
    Language : 
      - skill : English, Chinese Mandarin (native), Chinese Wenzhounese 
    Interest : 
      - skill : Meditation, Cooking, Programming
      
        
  # Icons
  icons :
    email:  zena.zheng@student.uva.nl 
    linkedin:  https://www.linkedin.com/in/zena-zheng-081308220/
    github: ZeningZheng
    gitlab: 
    bitbucket: 
    google_plus:


  # Disqus
  disqus_shortname :

# Pagination
paginate: 8
paginate_path: "blog/page:num"

# Build Ssttings
sass:
  sass_dir: _sass
  style: :compressed
gems: [jekyll-paginate]
bootstrap:
  assets: true
