# Site Settings
baseurl: ""
url : "https://zeningzheng.github.io"

# Blog Settings
theme_settings :
  title : Zening Zheng
  favicon : assets/favicon.ico

  # Profile Settings
  profile :
    image : assets/img/zena.jpg
    username : Zening (Zena) Zheng
    description : Master of Psychology in Behavioral Data Science, UvA
    Seeking for 2022 Intern
    experience :
      - start : 2017-05-03
        end : 2018-05-06
        experience : company name, title
    skills : 
      - skill : Python, R, SPSS,
    Language : 
      - skill : English, Chinese Mandarin (native), Chinese Wenzhounese 
      
        
  # Icons
  icons :
    email:  zena.zheng@student.uva.nl 
    linkedin:  https://www.linkedin.com/in/zena-zheng-081308220/
    github: https://github.com/ZeningZheng
    gitlab: 
    bitbucket: 
    google_plus:


  # Disqus
  disqus_shortname :

# Pagination
paginate: 8
paginate_path: "blog/page:num"

# Build Ssttings
sass:
  sass_dir: _sass
  style: :compressed
gems: [jekyll-paginate]
bootstrap:
  assets: true
