# Site Settings
baseurl: ""
url : "https://zeningzheng.github.io"

# Blog Settings
theme_settings :
  title : Zening Zheng
  favicon : assets/favicon.ico

  # Profile Settings
  profile :
    image : assets/img/zena.png
    username : Zening (Zena) Zheng
    description : Master of Psychology in Behavioral Data Science, UvA
    experience :
      - start : 2017-05-03
        end : 2018-05-06
        experience : company name, title
    skills : 
      - skill : Python, R, SPSS
        value : 85  # Percent value
        
  # Icons
  icons :
    email:  zena.zheng@student.uva.nl 
    linkedin:  https://www.linkedin.com/in/zena-zheng-081308220/
    github: https://github.com/ZeningZheng
    gitlab: 
    bitbucket: 
    google_plus:


  # Disqus
  disqus_shortname :

# Pagination
paginate: 5
paginate_path: "blog/page:num"

# Build Ssttings
sass:
  sass_dir: _sass
  style: :compressed
gems: [jekyll-paginate]
bootstrap:
  assets: true
